spring:
  profiles:
    active:
    - dev
---
server:
  port: 8001

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.mars.srpingcloud.entities       # 所有Entity别名类所在包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                       # mapper映射文件

spring:
   profiles: dev
   application: 
    name: microservicecloud-dept    # 很重要，对外暴露的微服务
   datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/cloudDB01              # 数据库名称
    username: root
    password: 123456
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间

# 注册eureka客户端
eureka:
  client:
    service-url:
#    集群注册配置，将当前微服务注册到三个Eureka服务中
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: microservicecloud-dept8001                # 指定客户端服务名称，在eureka管理界面中显示的status名称
    prefer-ip-address: true                                # 开启显示ip地址，status名称以ip地址访问
# 添加微服务的描述信息，通过status跳转到信息页面查看信息
info:
  app-name: mars-microservicecloud
  company.name: www.mars.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
  
---

server:
  port: 8002

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.mars.srpingcloud.entities       # 所有Entity别名类所在包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                       # mapper映射文件

spring:
   profiles: test
   application: 
    name: microservicecloud-dept    # 很重要，对外暴露的微服务
   datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/cloudDB02              # 数据库名称
    username: root
    password: 123456
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间

# 注册eureka客户端
eureka:
  client:
    service-url:
#    集群注册配置，将当前微服务注册到三个Eureka服务中
      defaultZone: http://eureka7002.com:7002/eureka/
  instance:
    instance-id: microservicecloud-dept8002                # 指定客户端服务名称，在eureka管理界面中显示的status名称
    prefer-ip-address: true                                # 开启显示ip地址，status名称以ip地址访问
# 添加微服务的描述信息，通过status跳转到信息页面查看信息
info:
  app-name: mars-microservicecloud
  company.name: www.mars.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$